sudo: false

env:
  - STACK_YAML=stack.yaml
  - STACK_YAML=stack-ghc-8.0.1.yaml

addons:
  apt:
    packages: libgmp-dev

install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version

script:
  - stack setup --no-terminal
  - stack build --ghc-options=-Werror --no-terminal
  - stack test --ghc-options=-Werror --no-terminal --coverage
  - stack haddock --no-terminal
  - cmp README.md servant-auth-server/executables/README.lhs

after_script:
  - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.3.0/shc-linux-x64-$GHCVER.tar.bz2 | tar -xj
  - ./shc combined all

cache:
  directories:
    - $HOME/.stack
